joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - iiwa_joint_1
     - iiwa_joint_2
     - iiwa_joint_3
     - iiwa_joint_4
     - iiwa_joint_5
     - iiwa_joint_6
     - iiwa_joint_7
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      iiwa_joint_1: {trajectory: 0.1, goal: 0.1}
      iiwa_joint_2: {trajectory: 0.1, goal: 0.1}
      iiwa_joint_3: {trajectory: 0.1, goal: 0.1}
      iiwa_joint_4: {trajectory: 0.1, goal: 0.1}
      iiwa_joint_5: {trajectory: 0.1, goal: 0.1}
      iiwa_joint_6: {trajectory: 0.1, goal: 0.1}
      iiwa_joint_7: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - iiwa_joint_1
     - iiwa_joint_2
     - iiwa_joint_3
     - iiwa_joint_4
     - iiwa_joint_5
     - iiwa_joint_6
     - iiwa_joint_7

