controller_list:
  - name: fake_manipulator_controller
    joints:
      - iiwa7_joint_1
      - iiwa7_joint_2
      - iiwa7_joint_3
      - iiwa7_joint_4
      - iiwa7_joint_5
      - iiwa7_joint_6
      - iiwa7_joint_7
  - name: fake_gripper_controller
    joints:
      - finger_joint